/*
 * This file is generated by jOOQ.
 */
package com.cikezxy.springbootsandbox.jooq.codegen.routines;


import java.math.BigDecimal;

import javax.annotation.Generated;

import com.cikezxy.springbootsandbox.jooq.codegen.Sakila;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.types.UByte;

/**
 * Provides a customizable report on best customers
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RewardsReport extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 1736175890;

    /**
     * The parameter <code>sakila.rewards_report.min_monthly_purchases</code>.
     */
    public static final Parameter<UByte> MIN_MONTHLY_PURCHASES = createParameter("min_monthly_purchases", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, false, false);

    /**
     * The parameter <code>sakila.rewards_report.min_dollar_amount_purchased</code>.
     */
    public static final Parameter<BigDecimal> MIN_DOLLAR_AMOUNT_PURCHASED = createParameter("min_dollar_amount_purchased", org.jooq.impl.SQLDataType.DECIMAL(10, 2), false, false);

    /**
     * The parameter <code>sakila.rewards_report.count_rewardees</code>.
     */
    public static final Parameter<Integer> COUNT_REWARDEES = createParameter("count_rewardees", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public RewardsReport() {
        super("rewards_report", Sakila.SAKILA);

        addInParameter(MIN_MONTHLY_PURCHASES);
        addInParameter(MIN_DOLLAR_AMOUNT_PURCHASED);
        addOutParameter(COUNT_REWARDEES);
    }

    /**
     * Set the <code>min_monthly_purchases</code> parameter IN value to the routine
     */
    public void setMinMonthlyPurchases(UByte value) {
        setValue(MIN_MONTHLY_PURCHASES, value);
    }

    /**
     * Set the <code>min_dollar_amount_purchased</code> parameter IN value to the routine
     */
    public void setMinDollarAmountPurchased(BigDecimal value) {
        setValue(MIN_DOLLAR_AMOUNT_PURCHASED, value);
    }

    /**
     * Get the <code>count_rewardees</code> parameter OUT value from the routine
     */
    public Integer getCountRewardees() {
        return get(COUNT_REWARDEES);
    }
}
